pipelines:
  mp-for-a-week:
    group: common
    label_template: "${COUNT}"
    materials:
      mp-for-a-week-git:
        git: https://github.com/ukparliament/mp-for-a-week.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release


environments:
  WebDEVCI:
    pipelines:
      - mp-for-a-week
